Stateful ApplyingChangesPage to prevent crash.
Apparently if the user clicks too fast in the last button of the Wizard
a crash could be generated due some sort of race condition in the Wizard
itself caused by a post frame callback previously scheduled to call
Wizard.next() being executed when the wizard was already at the last
page. Storing the previous stream data value and comparing to it before
scheduling the callback seems effective to prevent such condition. Think
of this as perfoming the scheduling only once at the moment of the
stream value transition and never after that.

A log of such event looks like this:

```
flutter: INFO subiquity_status: POST_RUNNING => ApplicationStatus(state: ApplicationState.DONE, confirmingTty: , error: null, cloudInitOk: true, interactive: true, echoSyslogId: subiquity_echo.14465, logSyslogId: , eventSyslogId: )
flutter: DEBUG subiquity_client: GET http://localhost/identity
flutter: DEBUG subiquity_client: ==> identity() {"realname": "u", "username": "u", "crypted_password": "", "hostname": ""}
flutter: INFO system_shutdown: request reboot (immediate: false)
flutter: INFO window: request window close
starting server
flutter: INFO window: window closed
flutter: INFO subiquity_client: Closing socket /home/cnihelton/Dev/Flutter_UDI/main/packages/ubuntu_wsl_setup/../subiquity_client/subiquity/.subiquity/socket
flutter: ERROR ubuntu_wsl_setup: Unhandled exception
        _AssertionError: 'package:wizard_router/src/wizard.dart': Failed assertion: line 324 pos 14: 'index < widget._routes.length - 1': `Wizard.next()` called from the last route /setup-complete.
\#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
\#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
\#2      WizardScopeState.next.nextRoute (package:wizard_router/src/wizard.dart:324:14)
\#3      WizardScopeState.next (package:wizard_router/src/wizard.dart:330:25)
\#4      ApplyingChangesPage.build.<anonymous closure>.<anonymous closure> (package:ubuntu_wsl_setup/pages/applying_changes/applying_changes_page.dart:46:44)
\#5      _TaskEntry.run.<anonymous closure> (package:flutter/src/scheduler/binding.dart:80:34)
\#6      Timeline.timeSync (dart:developer/timeline.dart:163:22)
\#7      _TaskEntry.run (package:flutter/src/scheduler/binding.dart:77:16)
\#8      SchedulerBinding.handleEventLoopCallback (package:flutter/src/scheduler/binding.dart:458:15)
\#9      SchedulerBinding._runTasks (package:flutter/src/scheduler/binding.dart:435:9)
\#10     _rootRun (dart:async/zone.dart:1418:47)
\#11     _CustomZone.run (dart:async/zone.dart:1328:19)
\#12     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
\#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
\#14     _rootRun (dart:async/zone.dart:1426:13)
\#15     _CustomZone.run (dart:async/zone.dart:1328:19)
\#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
\#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
\#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
\#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
\#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Lost connection to device.

```