named_event.h: add missing <string> include
Fixes a build issue that has suddenly appeared in the CI:
```
named_event.h(13,19): error C2039: 'string': is not a member of 'std'
```